import { 
  User, 
  Event, 
  Post, 
  Ticket, 
  Organizer, 
  Notification, 
  UserPreferences,
  NotificationPreferences,
  PrivacySettings,
  AccessibilitySettings,
  UserRole,
  EventCategory,
  EventStatus,
  EventVisibility,
  PostType,
  PostVisibility,
  AccessLevel,
  TicketType,
  TicketStatus,
  VenueType,
  PaymentMethod,
  NotificationType
} from '@/types';

// Mock user data
export const mockUsers: User[] = [
  {
    id: 'user-1',
    uid: 'user-1',
    email: 'john@example.com',
    username: 'john_doe',
    displayName: 'John Doe',
    bio: 'Event enthusiast and content creator',
    interests: ['music', 'technology', 'food', 'travel'],
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    coverUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=400&h=200&fit=crop',
    isVerified: true,
    isOrganizer: false,
    isAdmin: false,
    role: UserRole.USER,
    preferences: {
      notifications: {
        push: true,
        email: true,
        sms: false,
        inApp: true,
        quietHours: { enabled: false, start: '22:00', end: '08:00' },
        types: {
          event_reminder: true,
          event_update: true,
          event_cancelled: true,
          event_postponed: true,
          ticket_purchased: true,
          ticket_refunded: true,
          ticket_transferred: true,
          ticket_upgraded: true,
          new_follower: true,
          post_liked: true,
          post_commented: true,
          post_shared: true,
          new_post: true,
          gated_content: true,
          vip_content: true,
          event_approved: true,
          event_rejected: true,
          sales_update: true,
          system_update: true,
          security_alert: true,
          maintenance: true,
        },
      },
      privacy: {
        profileVisibility: 'public',
        activityStatus: true,
        dataSharing: true,
      },
      accessibility: {
        fontSize: 'medium',
        highContrast: false,
        reduceMotion: false,
      },
      theme: 'system',
      language: 'en',
      timezone: 'UTC',
    },
    stats: {
      followersCount: 1250,
      followingCount: 340,
      postsCount: 45,
      eventsAttended: 23,
      eventsCreated: 0,
      totalLikes: 8900,
      totalViews: 125000,
    },
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-08-15T00:00:00Z',
    lastActiveAt: '2024-08-15T00:00:00Z',
    isPrivate: false,
    isBlocked: false,
    blockedUsers: [],
  },
  {
    id: 'user-2',
    uid: 'user-2',
    email: 'sarah@example.com',
    username: 'sarah_events',
    displayName: 'Sarah Events',
    bio: 'Professional event organizer and party planner',
    interests: ['event-planning', 'business', 'networking', 'marketing'],
    avatarUrl: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face',
    coverUrl: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=400&h=200&fit=crop',
    isVerified: true,
    isOrganizer: true,
    isAdmin: false,
    role: UserRole.ORGANIZER,
    preferences: {
      notifications: {
        push: true,
        email: true,
        sms: false,
        inApp: true,
        quietHours: { enabled: false, start: '22:00', end: '08:00' },
        types: {
          event_reminder: true,
          event_update: true,
          event_cancelled: true,
          event_postponed: true,
          ticket_purchased: true,
          ticket_refunded: true,
          ticket_transferred: true,
          ticket_upgraded: true,
          new_follower: true,
          post_liked: true,
          post_commented: true,
          post_shared: true,
          new_post: true,
          gated_content: true,
          vip_content: true,
          event_approved: true,
          event_rejected: true,
          sales_update: true,
          system_update: true,
          security_alert: true,
          maintenance: true,
        },
      },
              privacy: {
          profileVisibility: 'public',
          activityStatus: true,
          dataSharing: true,
        },
        accessibility: {
          fontSize: 'medium',
          highContrast: false,
          reduceMotion: false,
        },
      theme: 'system',
      language: 'en',
      timezone: 'UTC',
    },
    stats: {
      followersCount: 3200,
      followingCount: 150,
      postsCount: 89,
      eventsAttended: 156,
      eventsCreated: 23,
      totalLikes: 15600,
      totalViews: 890000,
    },
    createdAt: '2023-06-10T00:00:00Z',
    updatedAt: '2024-08-15T00:00:00Z',
    lastActiveAt: '2024-08-15T00:00:00Z',
    isPrivate: false,
    isBlocked: false,
    blockedUsers: [],
  },
];

// Mock organizer data
export const mockOrganizers: Organizer[] = [
  {
    id: 'organizer-1',
    userId: 'user-2',
    user: mockUsers[1],
    companyName: 'Sarah Events LLC',
    description: 'Professional event organizer and party planner',
    logo: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=400&h=200&fit=crop',
    website: 'https://sarahevents.com',
    socialLinks: {
      instagram: '@sarahevents',
      twitter: '@sarahevents',
      facebook: 'sarahevents',
    },
    isVerified: true,
    verificationDate: '2023-06-10T00:00:00Z',
    verificationDocuments: ['business-license.pdf', 'insurance-cert.pdf'],
    events: [],
    followers: [],
    followersCount: 3200,
    totalEvents: 23,
    totalRevenue: 125000,
    averageRating: 4.8,
    settings: {
      autoApprovePosts: false,
      requireApproval: true,
      allowUserPosts: true,
      moderationLevel: 'medium',
      notificationPreferences: {
        push: true,
        email: true,
        sms: false,
        inApp: true,
        quietHours: { enabled: false, start: '22:00', end: '08:00' },
        types: {
          event_reminder: true,
          event_update: true,
          event_cancelled: true,
          event_postponed: true,
          ticket_purchased: true,
          ticket_refunded: true,
          ticket_transferred: true,
          ticket_upgraded: true,
          new_follower: true,
          post_liked: true,
          post_commented: true,
          post_shared: true,
          new_post: true,
          gated_content: true,
          vip_content: true,
          event_approved: true,
          event_rejected: true,
          sales_update: true,
          system_update: true,
          security_alert: true,
          maintenance: true,
        },
      },
    },
    createdAt: '2023-06-10T00:00:00Z',
    updatedAt: '2024-08-15T00:00:00Z',
  },
];

// Mock event data
export const mockEvents: Event[] = [
  {
    id: 'event-1',
    slug: 'summer-music-festival-2024',
    title: 'Summer Music Festival 2024',
    description: 'Join us for the biggest music festival of the summer! Featuring top artists from around the world, amazing food, and unforgettable experiences.',
    shortDescription: 'The biggest music festival of the summer',
    category: EventCategory.MUSIC,
    subcategory: 'festival',
    tags: ['music', 'festival', 'summer', 'live', 'outdoor'],
    coverImage: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&h=300&fit=crop',
    logo: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=150&h=150&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&h=300&fit=crop',
      'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&h=300&fit=crop',
    ],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    organizerId: 'organizer-1',
    organizer: mockOrganizers[0],
    location: {
      id: 'location-1',
      address: '123 Festival Grounds',
      city: 'Los Angeles',
      state: 'CA',
      country: 'USA',
      postalCode: '90210',
      latitude: 34.0522,
      longitude: -118.2437,
      formattedAddress: '123 Festival Grounds, Los Angeles, CA 90210',
    },
    venue: {
      id: 'venue-1',
      name: 'Downtown Festival Grounds',
      type: VenueType.OUTDOOR,
      address: {
        id: 'venue-location-1',
        address: '123 Festival Grounds',
        city: 'Los Angeles',
        state: 'CA',
        country: 'USA',
        postalCode: '90210',
        latitude: 34.0522,
        longitude: -118.2437,
        formattedAddress: '123 Festival Grounds, Los Angeles, CA 90210',
      },
      capacity: 50000,
      amenities: ['parking', 'wifi', 'food', 'bathrooms', 'first-aid'],
      accessibility: {
        wheelchairAccessible: true,
        accessibleParking: true,
        accessibleRestrooms: true,
        signLanguageInterpreters: false,
        audioDescription: false,
        serviceAnimalsAllowed: true,
        notes: 'Accessible venue with ramps and elevators',
      },
      parking: {
        available: true,
        free: false,
        cost: 25,
        capacity: 5000,
        accessibleSpaces: 100,
        notes: 'Parking available on-site',
      },
      photos: ['https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&h=300&fit=crop'],
      description: 'Large outdoor venue perfect for music festivals',
    },
    startDate: '2024-09-15T18:00:00Z',
    endDate: '2024-09-15T23:00:00Z',
    timezone: 'America/Los_Angeles',
    doorsOpen: '2024-09-15T17:00:00Z',
    doorsClose: '2024-09-15T22:30:00Z',
    status: EventStatus.ON_SALE,
    visibility: EventVisibility.PUBLIC,
    isActive: true,
    isVerified: true,
    isFeatured: true,
    capacity: 50000,
    soldOut: false,
    waitlistEnabled: true,
    waitlistCount: 1250,
    priceRange: {
      min: 75,
      max: 250,
      currency: 'USD',
    },
    currency: 'USD',
    likesCount: 8900,
    sharesCount: 1200,
    viewsCount: 45000,
    followersCount: 15600,
    posts: [],
    tickets: [],
    campaigns: [],
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2024-08-15T00:00:00Z',
    publishedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'event-2',
    slug: 'tech-conference-2024',
    title: 'Tech Conference 2024',
    description: 'The premier technology conference featuring the latest innovations, networking opportunities, and expert speakers.',
    shortDescription: 'Premier technology conference',
    category: EventCategory.BUSINESS,
    subcategory: 'conference',
    tags: ['technology', 'conference', 'networking', 'innovation'],
    coverImage: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=300&fit=crop',
    logo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=150&h=150&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=300&fit=crop',
    ],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    organizerId: 'organizer-1',
    organizer: mockOrganizers[0],
    location: {
      id: 'location-2',
      address: '456 Convention Center Blvd',
      city: 'San Francisco',
      state: 'CA',
      country: 'USA',
      postalCode: '94105',
      latitude: 37.7749,
      longitude: -122.4194,
      formattedAddress: '456 Convention Center Blvd, San Francisco, CA 94105',
    },
    venue: {
      id: 'venue-2',
      name: 'San Francisco Convention Center',
      type: VenueType.CONFERENCE_CENTER,
      address: {
        id: 'venue-location-2',
        address: '456 Convention Center Blvd',
        city: 'San Francisco',
        state: 'CA',
        country: 'USA',
        postalCode: '94105',
        latitude: 37.7749,
        longitude: -122.4194,
        formattedAddress: '456 Convention Center Blvd, San Francisco, CA 94105',
      },
      capacity: 10000,
      amenities: ['parking', 'wifi', 'food', 'bathrooms', 'first-aid', 'business-center'],
      accessibility: {
        wheelchairAccessible: true,
        accessibleParking: true,
        accessibleRestrooms: true,
        signLanguageInterpreters: true,
        audioDescription: true,
        serviceAnimalsAllowed: true,
        notes: 'Fully accessible venue',
      },
      parking: {
        available: true,
        free: false,
        cost: 35,
        capacity: 2000,
        accessibleSpaces: 50,
        notes: 'Parking garage available',
      },
      photos: ['https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=300&fit=crop'],
      description: 'Modern convention center in the heart of San Francisco',
    },
    startDate: '2024-10-20T09:00:00Z',
    endDate: '2024-10-22T18:00:00Z',
    timezone: 'America/Los_Angeles',
    doorsOpen: '2024-10-20T08:00:00Z',
    doorsClose: '2024-10-22T17:00:00Z',
    status: EventStatus.ON_SALE,
    visibility: EventVisibility.PUBLIC,
    isActive: true,
    isVerified: true,
    isFeatured: false,
    capacity: 10000,
    soldOut: false,
    waitlistEnabled: true,
    waitlistCount: 450,
    priceRange: {
      min: 299,
      max: 899,
      currency: 'USD',
    },
    currency: 'USD',
    likesCount: 3400,
    sharesCount: 890,
    viewsCount: 15600,
    followersCount: 8900,
    posts: [],
    tickets: [],
    campaigns: [],
    createdAt: '2024-05-15T00:00:00Z',
    updatedAt: '2024-08-15T00:00:00Z',
    publishedAt: '2024-05-15T00:00:00Z',
  },
];

// Mock post data
export const mockPosts: Post[] = [
  {
    id: 'post-1',
    eventId: 'event-1',
    event: mockEvents[0],
    authorId: 'user-1',
    author: mockUsers[0],
    type: PostType.VIDEO,
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&h=600&fit=crop',
    duration: 30000,
    aspectRatio: 9 / 16,
    caption: 'Amazing vibes at the Summer Music Festival! 🎵✨ #musicfestival #summer #vibes',
    hashtags: ['#musicfestival', '#summer', '#vibes', '#live'],
    mentions: [],
    visibility: PostVisibility.PUBLIC,
    accessLevel: AccessLevel.GENERAL,
    isPinned: false,
    isSponsored: false,
    likes: 1250,
    comments: 89,
    shares: 234,
    views: 15600,
    watchTime: 24000,
    completionRate: 0.8,
    isLiked: false,
    isSaved: false,
    isShared: false,
    createdAt: '2024-08-14T18:30:00Z',
    updatedAt: '2024-08-14T18:30:00Z',
  },
  {
    id: 'post-2',
    eventId: 'event-1',
    event: mockEvents[0],
    authorId: 'user-2',
    author: mockUsers[1],
    type: PostType.VIDEO,
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&h=600&fit=crop',
    duration: 45000,
    aspectRatio: 9 / 16,
    caption: 'Behind the scenes of the biggest music festival! 🎤🎸 #behindthescenes #music #festival',
    hashtags: ['#behindthescenes', '#music', '#festival', '#production'],
    mentions: [],
    visibility: PostVisibility.PUBLIC,
    accessLevel: AccessLevel.GENERAL,
    isPinned: false,
    isSponsored: false,
    likes: 890,
    comments: 67,
    shares: 145,
    views: 8900,
    watchTime: 36000,
    completionRate: 0.8,
    isLiked: true,
    isSaved: false,
    isShared: false,
    createdAt: '2024-08-14T16:45:00Z',
    updatedAt: '2024-08-14T16:45:00Z',
  },
  {
    id: 'post-3',
    eventId: 'event-2',
    event: mockEvents[1],
    authorId: 'user-2',
    author: mockUsers[1],
    type: PostType.VIDEO,
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=600&fit=crop',
    duration: 20000,
    aspectRatio: 9 / 16,
    caption: 'Tech Conference 2024 is going to be epic! 🚀💻 #techconference #innovation #technology',
    hashtags: ['#techconference', '#innovation', '#technology', '#future'],
    mentions: [],
    visibility: PostVisibility.PUBLIC,
    accessLevel: AccessLevel.GENERAL,
    isPinned: false,
    isSponsored: false,
    likes: 567,
    comments: 34,
    shares: 78,
    views: 4500,
    watchTime: 18000,
    completionRate: 0.9,
    isLiked: false,
    isSaved: true,
    isShared: false,
    createdAt: '2024-08-14T14:20:00Z',
    updatedAt: '2024-08-14T14:20:00Z',
  },
];

// Mock ticket data
export const mockTickets: Ticket[] = [
  {
    id: 'ticket-1',
    eventId: 'event-1',
    event: mockEvents[0],
    userId: 'user-1',
    user: mockUsers[0],
    ticketType: TicketType.GENERAL,
    accessLevel: AccessLevel.GENERAL,
    name: 'General Admission',
    description: 'General admission ticket for Summer Music Festival 2024',
    price: 75,
    currency: 'USD',
    originalPrice: 100,
    discount: 25,
    status: TicketStatus.ACTIVE,
    validFrom: '2024-09-15T17:00:00Z',
    validUntil: '2024-09-15T23:00:00Z',
    checkedInAt: undefined,
    qrCode: 'ticket-1-qr-code',
    qrData: {
      ticketId: 'ticket-1',
      eventId: 'event-1',
      userId: 'user-1',
      accessLevel: AccessLevel.GENERAL,
      timestamp: Date.now(),
      signature: 'mock-signature-1',
    },
    isTransferable: true,
    transferredFrom: undefined,
    transferredTo: undefined,
    addOns: [],
    upgrades: [],
    purchaseDate: '2024-07-15T10:30:00Z',
    paymentMethod: PaymentMethod.CREDIT_CARD,
    transactionId: 'txn-123456',
    createdAt: '2024-07-15T10:30:00Z',
    updatedAt: '2024-07-15T10:30:00Z',
  },
];

// Mock data service functions
export const mockDataService = {
  getUsers: () => Promise.resolve(mockUsers),
  getEvents: () => Promise.resolve(mockEvents),
  getPosts: () => Promise.resolve(mockPosts),
  getTickets: () => Promise.resolve(mockTickets),
  getUser: (id: string) => Promise.resolve(mockUsers.find(user => user.id === id)),
  getEvent: (id: string) => Promise.resolve(mockEvents.find(event => event.id === id)),
  getPost: (id: string) => Promise.resolve(mockPosts.find(post => post.id === id)),
  getTicket: (id: string) => Promise.resolve(mockTickets.find(ticket => ticket.id === id)),
};
